git:
    user:
        name: Constantinos Kouloumbris
        email: c@kouloumbris.com
        signingkey: 4D757F71C7B672E9
        github:
            username: ckr
    dependenciesBrew:
      - git
      - git-flow-avh
      - git-standup
      - git-quick-stats
    links:
      - { src: '{{ ansible_user_dir }}/bin/gn', dest: '{{ ansible_user_dir }}/bin/gn.py' }
